import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by VitePWA
precacheAndRoute(self.__WB_MANIFEST);

const CACHE_NAME = 'pawcare-v2';

// Activate immediately
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys => {
      return Promise.all(
        keys.filter(key => key !== CACHE_NAME && !key.startsWith('workbox-')).map(key => caches.delete(key))
      );
    })
  );
  self.clients.claim();
});

// Handle Push Notifications (Works even when app is closed/in background)
self.addEventListener('push', event => {
  let data = { title: 'PawCare AI', body: 'New notification' };
  try {
    data = event.data.json();
  } catch (e) {
    data = { title: 'PawCare AI', body: event.data ? event.data.text() : 'You have a new notification' };
  }

  const options = {
    body: data.body,
    icon: data.icon || '/pwa-192x192.png',
    badge: '/favicon.svg',
    vibrate: [500, 110, 500, 110, 450, 110, 200, 110, 170, 40, 450, 110, 200, 110, 170, 40, 500],
    data: data.data || { url: '/' },
    requireInteraction: true,
    tag: data.tag || 'pawcare-alarm',
    renotify: true,
    actions: [
      { action: 'open', title: '🐾 Open App' },
      { action: 'dismiss', title: 'Dismiss' }
    ],
    silent: false
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

// Handle notification click
self.addEventListener('notificationclick', event => {
  event.notification.close();
  
  const action = event.action;
  if (action === 'dismiss') return;

  const urlToOpen = event.notification.data?.url || '/';
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(windowClients => {
      // Try to focus an existing window
      for (const client of windowClients) {
        if ('focus' in client) {
          client.navigate(urlToOpen);
          return client.focus();
        }
      }
      // Open a new window if none exists
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});

// Handle notification close
self.addEventListener('notificationclose', event => {
  console.log('[SW] Notification dismissed:', event.notification.tag);
});
